### ISSUE TITLE
upgrade gems 

### ISSUE THREAD

**Issue by bradfordcondon** [statonlab/hardwoods_tripal_showcase#13]
abdullah cant help maintain as easily because my gems are out of date.  update

```
Traceback (most recent call last):
    10: from /usr/local/bin/jekyll:23:in `<main>'
     9: from /usr/local/bin/jekyll:23:in `load'
     8: from /usr/local/lib/ruby/gems/2.5.0/gems/jekyll-3.8.2/exe/jekyll:11:in `<top (required)>'
     7: from /usr/local/lib/ruby/gems/2.5.0/gems/jekyll-3.8.2/lib/jekyll/plugin_manager.rb:50:in `require_from_bundler'
     6: from /usr/local/lib/ruby/gems/2.5.0/gems/bundler-1.16.2/lib/bundler.rb:107:in `setup'
     5: from /usr/local/lib/ruby/gems/2.5.0/gems/bundler-1.16.2/lib/bundler/runtime.rb:26:in `setup'
     4: from /usr/local/lib/ruby/gems/2.5.0/gems/bundler-1.16.2/lib/bundler/runtime.rb:26:in `map'
     3: from /usr/local/Cellar/ruby/2.5.1/lib/ruby/2.5.0/forwardable.rb:229:in `each'
     2: from /usr/local/Cellar/ruby/2.5.1/lib/ruby/2.5.0/forwardable.rb:229:in `each'
     1: from /usr/local/lib/ruby/gems/2.5.0/gems/bundler-1.16.2/lib/bundler/runtime.rb:31:in `block in setup'
/usr/local/lib/ruby/gems/2.5.0/gems/bundler-1.16.2/lib/bundler/runtime.rb:313:in `check_for_activated_spec!': You have already activated jekyll-watch 2.0.0, but your Gemfile requires jekyll-watch 1.5.1. Prepending `bundle exec` to your command may solve this. (Gem::LoadError)
```

**Comment by bradfordcondon** [comment]
fixed by managing which ruby version is in use, and rerunning bundle install/bundle clean --force.
